server:
  port: 8080
app:
  prefix: /api/v1
#    userService: /api/v1/user-service
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      defaultFilters:
        - AddRequestHeader=X-Request-Foo, Bar
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://localhost:8081
#          uri: lb://user-service
          predicates:
            - Path=${app.prefix}/user-service/** # Đường dẫn mà API Gateway sẽ lắng nghe để điều hướng đến service tương ứng.
#          filters:
#            - StripPrefix=2 # phía user-service do phía user-service không có tiền tố /api/v1 => StripPrefix=2
#            - RewritePath=/api/v1/users/(?<segment>.*), /user-service/$\{segment} # Thay đổi đường dẫn để phù hợp với user-service.
# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/