server:
  port: 2004
app:
  prefix: /api/v1
#    userService: /api/v1/user-service
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      defaultFilters:
        - AddRequestHeader=X-Request-Foo, Bar
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.prefix}/users/** # Đường dẫn mà API Gateway sẽ lắng nghe.
          filters:
            #- StripPrefix=2 # phía user-service do phía user-service không có tiền tố /api/v1 => StripPrefix=2
            - RewritePath=/api/v1/users/(?<segment>.*), /user-service/$\{segment} # Thay đổi đường dẫn để phù hợp với user-service.



